server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    encoding: UTF-8
    basename: i18n.login

